resolver: lts-20.7
  # compiler: ghc-9.2.2
extra-deps:
  # - bitvec-1.0.2.0
  # - mod-0.1.0.0
  # - poly-0.4.0.0
  # - semirings-0.5.3
  # - vector-algorithms-0.8.0.3
  - protolude-0.3.2
  # - integer-gmp-1.0.3.0
  # - QuickCheck-2.14
